<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="../style/style.css">
    <link rel="stylesheet" href="../style/navstyle.css">
    <link rel="stylesheet" href="../style/knihastyle.css">
    <script src="../script/filterScript.js" defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>

<body>

    <header>
        <h1>Knyhy na maturak hyhy</h1>
    </header>

    <div class="navigation">
        <nav>
            <ul>
                <li><a href="/index.html"><span>Hlavní stánka</span></a></li>
                <li><a href="/kniha.html"><span>Knihy</span></a></li>
                <li><a href=""><span>Gramatika</span></a></li>
                <li><a href=""><span>Materiály</span></a></li>
                <li class="dropdown" id="profil">
                    <a href=""><span>Profil</span></a>
                    <div class="dropdown-content">
                        <a href="">Nastavení</a>
                        <a href="">Odhlásit se</a>
                    </div>
                </li>
            </ul>
        </nav>
    </div>

    <main>
        <div class="container">
            
            <div id="filterbackground">

                <!-- Dodělat animace nahoru zpět a roll dolů s posunem osy y -->
                <div class="filter">

                    <div class="dropdown1">
                        <button class="dropbtn1">Autoři</button>
                        
                        <div id="dropdownContent1" class="dropdown-content1">
                            <input type="text" placeholder="textový filtr"><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                        </div>

                    </div>

                    <div class="dropdown1">
                        <button class="dropbtn1">Období</button>
                        
                        <div id="dropdownContent1" class="dropdown-content1">
                            <input type="text" placeholder="textový filtr"><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                        </div>

                    </div>

                    <div class="dropdown1">
                        <button class="dropbtn1">Knihy</button>
                        
                        <div id="dropdownContent1" class="dropdown-content1">
                            <input type="text" placeholder="textový filtr"><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                     
                        </div>

                    </div>


                </div>
            </div>

            <div class="text">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo inventore similique ut accusantium veritatis aliquam exercitationem, vero voluptates quidem minima quae earum, enim eum magnam velit rerum non odit quod.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo inventore similique ut accusantium veritatis aliquam exercitationem, vero voluptates quidem minima quae earum, enim eum magnam velit rerum non odit quod.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo inventore similique ut accusantium veritatis aliquam exercitationem, vero voluptates quidem minima quae earum, enim eum magnam velit rerum non odit quod.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo inventore similique ut accusantium veritatis aliquam exercitationem, vero voluptates quidem minima quae earum, enim eum magnam velit rerum non odit quod.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo inventore similique ut accusantium veritatis aliquam exercitationem, vero voluptates quidem minima quae earum, enim eum magnam velit rerum non odit quod.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo inventore similique ut accusantium veritatis aliquam exercitationem, vero voluptates quidem minima quae earum, enim eum magnam velit rerum non odit quod.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo inventore similique ut accusantium veritatis aliquam exercitationem, vero voluptates quidem minima quae earum, enim eum magnam velit rerum non odit quod.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo inventore similique ut accusantium veritatis aliquam exercitationem, vero voluptates quidem minima quae earum, enim eum magnam velit rerum non odit quod.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo inventore similique ut accusantium veritatis aliquam exercitationem, vero voluptates quidem minima quae earum, enim eum magnam velit rerum non odit quod.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo inventore similique ut accusantium veritatis aliquam exercitationem, vero voluptates quidem minima quae earum, enim eum magnam velit rerum non odit quod.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo inventore similique ut accusantium veritatis aliquam exercitationem, vero voluptates quidem minima quae earum, enim eum magnam velit rerum non odit quod.</p>

                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo inventore similique ut accusantium veritatis aliquam exercitationem, vero voluptates quidem minima quae earum, enim eum magnam velit rerum non odit quod.</p>
            </div>
     

    </main>

    <footer>
        asdasdsd
    </footer>

</body>

</html>
