    <script src="../script/filterScript.js" defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<?php
 $hlavickyTabulky = [ // NASTAVENI HLAVICEK TABULKY
        "Kniha",
        "Autor",
        "Obdobi"
    ];

    $data = array(); // NASTAVENI RADKU TABULKY
    foreach ($this->data['vsechnyKnihy'] as $prispevek) {
        $data[] = array(
            [$prispevek['nazevKniha'], "kniha/" . $prispevek['idKniha']],
            [$prispevek['jmenoAutora']." ".$prispevek['prijmeniAutora'] , "autor/" . $prispevek['idAutora']],
            [$prispevek['nazevObdobi'], "prispevky/knihy/obdobi/" . $prispevek['idObdobi']],
        );
    }
?>

<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        padding: 0 10px;
    }
</style>

<div class="container">
            
            <div id="filterbackground">

                <!-- Dodělat animace nahoru zpět a roll dolů s posunem osy y -->
                <div class="filter">

                    <div class="dropdown1">
                        <button class="dropbtn1">Autoři</button>
                        
                        <div id="dropdownContent1" class="dropdown-content1">
                            <input type="text" placeholder="textový filtr"><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                        </div>

                    </div>

                    <div class="dropdown1">
                        <button class="dropbtn1">Období</button>
                        
                        <div id="dropdownContent1" class="dropdown-content1">
                            <input type="text" placeholder="textový filtr"><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                        </div>

                    </div>

                    <div class="dropdown1">
                        <button class="dropbtn1">Knihy</button>
                        
                        <div id="dropdownContent1" class="dropdown-content1">
                            <input type="text" placeholder="textový filtr"><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                            <label for="">a</label>
                            <input type="checkbox" name="" id=""><br>
                     
                        </div>

                    </div>


                </div>
            </div>

            <div class="text">
                <table>
                    <thead>
                        <?php // VLOZENI HLAVICEK TABULKY
                            foreach ($hlavickyTabulky as $hlavicka) {
                                echo "<th>$hlavicka</th>";
                            }
                        ?>
                    </thead>

                    <tbody>
                        <?php
                            foreach ($data as $radek){ // VKLADANI RADKU S DATY
                                echo "<tr>";
                                foreach ($radek as $value) {
                                    echo "<td><a href='$value[1]'>$value[0]</a></td>";
                                }
                                echo "</tr>";
                            }
                        ?>
                    </tbody>

                </table>
            

            </div>





<p><?php // JESTLIZE JE CHYBA, TAK UKAZ ZPRAVU A ZOBRAZ ODKAZ NA VSECHNY
    if (isset($_SESSION["zpravy"]["knihy"]["chybaNacteni"])) {
        echo $_SESSION["zpravy"]["knihy"]["chybaNacteni"] ;
        echo "<br>";
        echo "<a href='knihy'>Zobrazit vsechny</a>";
    }

    ?>
</p>
