<style>
    .hidden{
        display: none;
    }
</style>

<script src="../js/filterScript.js" defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!--    <pre>-->
<!--        --><?php //print_r($this->data['vsechnyKnihyFiltr']) ?>
<!--    </pre>-->


    <?php


    $data = array(); // NASTAVENI RADKU TABULKY
    foreach ($this->data['vsechnyKnihyFiltr'] as $prispevek) {
        $data[] = array(
            "odkazFotky" => "odkaz", ///////////////////////////////////// imgsrc vymenit podle databaze ////$prispevek['imgSrc']
            "nazevKnihy" => $prispevek['nazevKniha'], "idKnihy" =>  $prispevek['idKniha'],
            "jmenoAutora" => $prispevek['jmenoAutora'] . (!empty($prispevek['prijmeniAutora']) ? ' ' . $prispevek['prijmeniAutora'] : ''),
            "idAutora" => $prispevek['idAutora'],
            "nazevObdobi" => $prispevek['nazevObdobi'], "idObdobi" =>$prispevek['idObdobi']
        );
    }


    ?>

<div class="container">
        <div id="filterbackground">
            <div class="filter">
                <h3>Filtr</h3>
                <button class="resetFilter" type="button">Filter reset</button>
                <div class="dropdown1">
                    <button class="dropbtn1">Knihy</button>
                    <div id="dropdownContent1" class="dropdown-content1">
                        <input type="text" id="TextFilterKnihy" placeholder="textový filtr"><br>
                        <label for="povinneKnihyInput">Zobrazit pouze moje vybrane</label>
                        <input type="checkbox" class="povinneKnihy" id="povinneKnihyInput" <?= (isset($_SESSION['uzivatel']) ? '' : 'disabled') ?>>
                    </div>
                </div>
                <div class="dropdown1">
                    <button class="dropbtn1">Autoři</button>
                    <div id="dropdownContent1" class="dropdown-content1">
                        <label for="TextFilterAutori"></label>
                        <input type="text" id="TextFilterAutori" placeholder="textový filtr"><br>
                        <?php foreach ($this->data['vsichniAutori'] as $autor): ?>
                            <div class="autorFilter" autorId="<?= $autor['Id'] ?>">
                                <label for=""><?= $autor['Jmeno']." ".$autor['Prijmeni'] ?></label>
                                <input type="checkbox" id="">
                            </div>
                        <?php endforeach ?>
                    </div>
                </div>
                <div class="dropdown1">
                    <button class="dropbtn1">Období</button>
                    <div id="dropdownContent1" class="dropdown-content1">
                        <?php foreach ($this->data['vsechnyObdobi'] as $obdobi): ?>
                            <div class="obdobiFilter" obdobiId="<?= $obdobi['Id'] ?>">
                                <label for=""><?= $obdobi['Nazev'] ?></label>
                                <input type="checkbox" id="">
                            </div>
                        <?php endforeach ?>
                    </div>
                </div>
            </div>
        </div>


        <div class="text">
            <div class="row_info" style="display: flex; flex-wrap: wrap; justify-content: center;">
                <?php foreach ($data as $row) : ?>
                    <div class="knihainfo" knihaId="<?= $row['idKnihy'] ?>" autorId="<?= $row['idAutora'] ?>" obdobiId="<?= $row['idObdobi'] ?>">
                    <h4><a class="nazevKnihy" href="kniha/<?=$row['idKnihy'] ?>"><?=$row['nazevKnihy'] ?></a></h4>
                    <div class="wrap">
        <div class="perspective">
          <div class="book-wrap">                          <!--Místo url přidat odkaz na obrázky -->
            <div class="book book-1"style="background: url(https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e25b3ac3-7ce4-4af7-8a36-7c1ddbee5532/dfdyafz-8bdc6334-be5d-4d3e-b142-10fe8921639a.png/v1/fit/w_828,h_1210,q_70,strp/_ota__book_cover_design_1_by_jastra93_dfdyafz-414w-2x.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTg3MSIsInBhdGgiOiJcL2ZcL2UyNWIzYWMzLTdjZTQtNGFmNy04YTM2LTdjMWRkYmVlNTUzMlwvZGZkeWFmei04YmRjNjMzNC1iZTVkLTRkM2UtYjE0Mi0xMGZlODkyMTYzOWEucG5nIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.sF6yQoNssWVOjpeIVbuo2iczCWZfZ2LT_uGjTjTD590) black no-repeat center center;
                background-size: cover;
                width: var(--book-width);
                height: var(--book-height);
                position: absolute;
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                margin: auto;
                cursor: pointer;
                }"></div>


            <div class="title book-1"></div>
            <div class="book-back book-1">
              <div class="text">

                <p><span>
                    <div class="cell autorDiv">
                        <a class="jmenoAutora" href="autor/<?=$row['idAutora'] ?>"><?=$row['jmenoAutora'] ?></a>
                    </div>
                    </span><br>
                    <span>
                        <div class="cell obdobiDiv">
                            <a class="nazevObdobi" href="knihy/obdobi/<?=$row['idObdobi'] ?>"><?=$row['nazevObdobi'] ?></a>
                        </div>
                    </span>
                    </p>


                    <form action="" method="post">
                        <input type="hidden" name="idKnihy" value="<?= $row['idKnihy'] ?>">
                        <?php
//                        print_r($this->data['povinneKnihy']);
                        if (empty($this->data['povinneKnihy'])) {
                            echo '<input type="submit" class="addToLibraryBtn" name="type" value="pridat_do_povinnych" '.(isset($_SESSION['uzivatel']) ? '' : 'disabled').'>';
                        } else {
                            $isInPovinneKnihy = false;
                            foreach ($this->data['povinneKnihy'] as $povinneKnihy) {
                                if ($povinneKnihy['knihaId'] == $row['idKnihy']) {
                                    $isInPovinneKnihy = true;
                                    break;
                                }
                            }
                            if ($isInPovinneKnihy) {
                                echo '<input type="submit" class="addToLibraryBtn povinnaKniha" name="type" value="odebrat z povinnych">';
                            } else {
                                echo '<input type="submit" class="addToLibraryBtn" name="type" value="pridat do povinnych">';
                            }
                        }
                        ?>
                    </form>

                    <povinnostKnihy val="<?php echo (isset($isInPovinneKnihy)) ? $isInPovinneKnihy : false; ?>"></povinnostKnihy>
              </div>
            </div>
          </div>
        </div>
        <p><?php // JESTLIZE JE CHYBA, TAK UKAZ ZPRAVU A ZOBRAZ ODKAZ NA VSECHNY
        if (isset($_SESSION["zpravy"]["knihy"]["chybaNacteni"])) {
            echo $_SESSION["zpravy"]["knihy"]["chybaNacteni"] ;
            echo "<br>";
            echo "<a href='knihy'>Zobrazit vsechny</a>";
        }

        ?>
    </p>
      </div>

    <script>
        $(document).ready(function(){
            $(".book").mouseenter(function(){
                $(this).parent(".book-wrap").addClass("rotate");
            });

            $(".book").mouseleave(function(){
                $(this).parent(".book-wrap").removeClass("rotate");
            });

            $(".book").click(function(){
                $(this).parent(".book-wrap").addClass("flip");
            });

            $(".book-back").click(function(){
                $(this).parent(".book-wrap").removeClass("flip");
            });
        });
    </script>
                    </div>
                <?php endforeach ?>
                <p id="zadneKnihy" class="hidden">Filtru neodpovidaji zadne knihy</p>
            </div>
        </div>
    </div>


</div>
<!---
<script>

    $(document).ready(function() {
        $('.addToLibraryBtn').click(function() {
            var bookTitle = $(this).siblings('a').text();
            addToLibrary(bookTitle);
        });

        function addToLibrary(bookTitle) {

            console.log('Adding book to library: ' + bookTitle);
        }
    });

</script>

Získávání textu z textového filtru -->


    <!--
    <script>
            const inputElement = document.getElementById('TextFilter1');

        inputElement.addEventListener('keydown', (event) => {
            if (event.key === 'Enter') {
                 console.log('Entered text:', inputElement.value);
            }
        });
    </script>
    ---->
    




