<div class="container">
    <div class="form-container">
        <h2 id="nazevKviz"><?=$this->data['kviz']['Nazev']?></h2>
        <h3><?=$this->data['kviz']['jmeno']?> <?=$this->data['kviz']['prijmeni']?></h3>

        <form action="" method="post">
            <div class="content">
                <?=$this->data['kviz']['Obsah']?>
            </div>
            <input type="submit" value="Submit">
        </form>

        <h3 id="date">
            <p><?=$this->data['kviz']['DatumNahrani']?></p>
        </h3>
    </div>
</div>