<main>

    <div>
        <input type="text" name="ICO" id="ICO" placeholder="IČO">
        <input type="button" id="button" value="Vyhledat">

    </div>

    <script src="js/hledatSkolu.js"></script>
    <script>
        document.getElementById("button").addEventListener("click", async function () {
            const input = document.getElementById("ICO"); //00602132
            //TODO nějakým způsobem získat atribut obchodniJmeno z arraye skola do promenne nazev

            let response = await fetch("https://ares.gov.cz/ekonomicke-subjekty-v-be/rest/ekonomicke-subjekty/" + input.value).then(response => {
                return response.json();
            })

            console.log(response);

            let nazev = response.obchodniJmeno;
            console.log(nazev);

            /*
            skola.then(result => {
                const obchodniJmeno = result.value.obchodniJmeno;
                console.log(obchodniJmeno);
            }).catch(error => {
                console.error('Chyba při získávání dat:', error);
            })

             */

            let date = new Date();
            date.setTime(date.getTime() + (24 * 60 * 60 * 1000));

            document.cookie = "nazev=" + nazev + "; expires=" + date.toGMTString() + "; path=/";
            document.cookie = "ico=" + input.value + "; expires=" + date.toGMTString() + "; path=/";

            window.location.replace("pridatSkolu");
        });
    </script>

</main>