<form action="" method="post">

    <div>

        <div>
            <label for="">Email</label>
            <input type="email" name="email" id=""> <!--nepovinne-->
        </div>

        <div>
            <label for="">Heslo</label>
            <input type="password" name="heslo" id="">
        </div>

    </div>
    <input type="submit" value="Odeslat">
    <p id="chybnePrihlaseni" style="display: none">Chyba autentikace zadejte znovu</p>


</form