
<div id="LoginOutline">

    <h3>Přihlaste se</h3>

        <form action="" method="post">

            <div id="LogInputs">

                <input type="email" name="email" id="email" placeholder="Email">
                <input type="password" name="heslo" id="heslo" placeholder="Heslo">
                <input type="submit" value="Login">
                    
                <p id="chybnePrihlaseni" style="display: none">Chyba autentikace zadejte znovu</p>
                
                <a href="registrace">Registrace</a>
                
            </div>

        </form>


</div>
