<div id="id">
    <?php
    // HLAVICKY TABULKY
    $hlavickyTabulky = [
        "Nazev prispevku",
        "Kniha",
        "Autor",
        "Obdobi",
        "Uzivatel"
    ];

    $data = array(); // NASTAVENI RADKU TABULKY
    foreach ($this->data['vsechnyPrispevky'] as $prispevek) {
        $data[] = array(
            [$prispevek['nazevPrispevku'], "prispevek/" . $prispevek['idPrispevku']],
            [$prispevek['nazevKniha'], "kniha/" . $prispevek['idKniha']],
            [$prispevek['jmenoAutora']." ".$prispevek['prijmeniAutora'] , "autor/" . $prispevek['idAutora']],
            [$prispevek['nazevObdobi'], "prispevky/knihy/obdobi/" . $prispevek['idObdobi']],
            [$prispevek['jmenoUzivatele']." ".$prispevek['prijmeniUzivatele'], "uzivatel/" . $prispevek['idUzivatele']],
        );
    }
    ?>

    <table>
        <thead>
            <?php // VLOZENI HLAVICEK TABULKY
            foreach ($hlavickyTabulky as $hlavicka) {
                echo "<th>$hlavicka</th>";
            }
            ?>
        </thead>
        <tbody>
        <?php
        foreach ($data as $radek){ // VKLADANI RADKU S DATY
            echo "<tr>";
            foreach ($radek as $value) {
                echo "<td><a href='$value[1]'>$value[0]</a></td>";
            }
            echo "</tr>";
        }
        ?>
        </tbody>
    </table>

    <p><?php // JESTLIZE JE CHYBA, TAK UKAZ ZPRAVU A ZOBRAZ ODKAZ NA VSECHNY
        if (isset($_SESSION["zpravy"]["prispevky"]["chybaNacteni"])) {
            echo $_SESSION["zpravy"]["prispevky"]["chybaNacteni"] ;
            echo "<br>";
            echo "<a href='prispevky'>Zobrazit vsechny</a>";
        }
        ?>
    </p>
</div>