<script src="../js/registrace.js"></script>
<div class="profilZmena">

    <h3>Registrace</h3>

    <form action="" method="post">

        <input type="text" name="jmeno" id="" placeholder="Jméno" required>
        <input type="text" name="prijmeni" id="" placeholder="Příjmení">
        <input type="email" name="email" id="" placeholder="Email" required> 
        <input type="password" name="heslo" id="" placeholder="Heslo">
        <input type="password" name="heslo2" id="" placeholder="Potvrďte heslo">
        
        <input type="submit" value="Odeslat">
        
    </form>
</div>

<div class="profilZmena" id="autentikacniOkenkoDiv" style="display: none">
    <div id="autentikacniOkenkoDiv" >
        <form action="" method="post">
            
            <input type="text" name="authCode" id="" maxlength="6" placeholder="Zadejte autentikacni znaky poslane na email" required>
            <input type="submit" value="Odeslat">
        </form>
    </div>
    <p id="chyboveHlaseni"><?= ($_SESSION["zpravy"]["registrace"]["chyba"] ?? "") ?></p>
</div>