<!DOCTYPE html>
<html lang="cs">
<head>
    <base href="/">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MVC app I3B S1 22/23</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="uvod">Úvod</a></li>
            <li><a href="faktura">Faktura</a></li>
            <li><a href="body">Body</a></li>
        </ul>
    </nav>
    <?php
        $this->kontroler->vypisPohled();
    ?>
</body>
</html>