<?php

/*
//TODO vyměnit URL při hostingu
//header( "Location: ".(empty($_SERVER['HTTPS']) ? 'http' : 'https') . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"."?authWindow" );

$URL = "//" . $_SERVER['HTTP_HOST'];
*/

?>

<!DOCTYPE html>
<html lang="cs">
<head>
    <base href="/">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $this->kontroler->data["title"]?> | Knihovna</title> <!-- TODO DOPLNIT AUTOMATICKÉ TITLES -->

    <?php
        foreach ($this->kontroler->cssCesty as $cesta)
        {
            echo '<link rel="stylesheet" href="style/'. $cesta .'">';
        }
    ?>
    <link rel="icon" type="image/x-icon" href="obrazky/favicon.ico">
</head>
<body>
<header>
    <h1><a href="">Knyhy na maturak hyhy</a></h1>
</header>

<div class="navigation">
    <nav>
        <ul>
            <li><a href="knihy"><span>Knihy</span></a></li>
            <li><a href=""><span>Gramatika</span></a></li>
            <li><a href="prispevky"><span>Materiály</span></a></li>

            <?php
            if(!$this->kontroler->prihlasenyUzivatel)
            {
                ?>
                <li><a href="prihlaseni"><span>Přihlásit</span></a></li>
                <?php
            }
            else
            {
                ?>
                <li class="dropdown" id="profil">
                    <a href=""><span>Profil</span></a>
                    <div class="dropdown-content">
                        <a href="">Nastavení</a>
                        <a href="odhlaseni">Odhlásit se</a>
                    </div>
                </li>
                <?php
            }
            ?>

        </ul>
    </nav>
</div>




<?php
    $this->kontroler->vypisPohled();
?>


</body>
</html>