<?php
//TODO vyměnit URL při hostingu
//header( "Location: ".(empty($_SERVER['HTTPS']) ? 'http' : 'https') . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"."?authWindow" );

$URL = "//" . $_SERVER['HTTP_HOST'];


?>

<!DOCTYPE html>
<html lang="cs">
<head>
    <base href="/">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Knyha</title>
    <link rel="stylesheet" href="style/style.css">
    <link rel="icon" type="image/x-icon" href="obrazky/favicon.ico">
</head>
<body>
<header>
    <h1>Knyhy na maturak hyhy</h1>
</header>

<div class="navigation">
    <nav>
        <ul>
            <li><a href="uvod"><span>Knihy</span></a></li>
            <li><a href=""><span>Gramatika</span></a></li>
            <li><a href=""><span>Materiály</span></a></li>
            <li class="dropdown" id="profil">
                <a href=""><span>Profil</span></a>
                <div class="dropdown-content">
                    <a href="">Nastavení</a>
                    <a href="">Odhlásit se</a>
                </div>
            </li>
        </ul>
    </nav>
</div>




<?php
    $this->kontroler->vypisPohled();
?>


</body>
</html>