<main>

    <div class="container">

        <div id="text">

            <span id="daily">
                    <div id="dailyoutline">
                        <h3>Daily questy</h3>
                        <div class="dailyquest">

                            <!-- Dodat podmínkování se zprávou, pokud je vše hotovo tak nějak to dát vědět (zaškrtnutí / zpáva o dokončení všeho) -->


                            <!-- dodat linky na daily questy a dodělat generaci questů podle generace-->
                            <div id="dailyknihy">
                                <div id="daily_kniha_zadani">
                                    <p>Začít denní quest -knihy-</p>
                                    <a href="#"><button>začít</button></a>
                                </div>
                                <div id="daily_kniha_zadani">
                                    <p>Začít denní quest -knihy-</p>
                                    <a href="#"><button>začít</button></a>
                                </div>

                            </div>
                            <div id="dailygramatika">
                                <div id="daily_gramatika_zadani">
                                    <p>Začít daily quest -gramatika-</p>
                                    <a href="#"><button>začít</button></a>
                                </div>
                                <div id="daily_gramatika_zadani">
                                    <p>Začít daily quest -gramatika-</p>
                                    <a href="#"><button>začít</button></a>
                                </div>

                            </div>
                        </div>
                    </div>
                </span>


            <div id="section">
                <h3>Cvičení</h3>
            </div>


            <div id="divbars">



                <div>
                    <img src="" alt="">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>
                </div>

                <div>
                    <img src="" alt="">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>
                </div>

                <div>
                    <img src="" alt="">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>                
                </div>

                <div>
                    <img src="" alt="">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>
                </div>

                <div>
                    <img src="" alt="">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>
                </div>

                <div>
                    <img src="" alt="">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>
                </div>

            </div>


        </div>



        <div id="sidediv">

            <div id="profile-info">
                <h3>Profil</h3>
                <p>Jmeno: <?php echo $this->data["jmeno"] ?></p>
                <p>Streak:</p>
            </div>


            

            
            <div id="nastenka">
                
                <div id="nadpis">
                    <h3>Nástěnka</h3>
                </div>
                   
                <div id="scroler">
                    
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                    
                </div>

            </div>
            

        </div>

    </div>

</main>


<footer>
    <p>Blagablugah</p>
</footer>