<main>

    <div class="container">

        <div id="text">

            <span id="daily">
                    <div id="dailyoutline">
                        <h3>Daily questy</h3>
                        <div class="dailyquest">

                            <!-- Dodat podmínkování se zprávou, pokud je vše hotovo tak nějak to dát vědět (zaškrtnutí / zpáva o dokončení všeho) -->


                            <!-- dodat linky na daily questy a dodělat generaci questů podle generace-->
                            <div id="dailyknihy">
                                <div id="daily_kniha_zadani">
                                    <p>Začít denní quest -knihy-</p>
                                    <a href="#"><button>začít</button></a>
                                </div>
                                <div id="daily_kniha_zadani">
                                    <p>Začít denní quest -knihy-</p>
                                    <a href="#"><button>začít</button></a>
                                </div>

                            </div>
                            <div id="dailygramatika">
                                <div id="daily_gramatika_zadani">
                                    <p>Začít daily quest -gramatika-</p>
                                    <a href="#"><button>začít</button></a>
                                </div>
                                <div id="daily_gramatika_zadani">
                                    <p>Začít daily quest -gramatika-</p>
                                    <a href="#"><button>začít</button></a>
                                </div>

                            </div>
                        </div>
                    </div>
                </span>


            <div id="section">
                <h3>Cvičení</h3>
            </div>


            <div id="divbars">

            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script src="../js/linkUkoly.js"></script>


                <div id="KvizDiv">
                <a href="vytvareniKvizu"><img src="https://cdn4.iconfinder.com/data/icons/defaulticon/icons/png/256x256/help.png" alt=""></a>
                <p><a href="vytvareniKvizu">Kviz</a></p>
                </div>

                <div id="KvizDiv">
                <a href="vytvareniPrispevku"><img src="https://cdn4.iconfinder.com/data/icons/defaulticon/icons/png/256x256/help.png" alt=""></a>
                <p><a href="vytvareniPrispevku">prispevky</a></p>
                </div>


            </div>


        </div>



        <div id="sidediv">

            <div id="profile-info">
                <h3>Profil</h3>
                <p>Jmeno: <?php echo $this->data["jmeno"] ?></p>
                <p>Streak:</p>
            </div>


            

            
            <div id="nastenka">
                
                <div id="nadpis">
                    <h3>Nástěnka</h3>
                </div>
                   
                <div id="scroler">
                    
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                    
                </div>

            </div>
            

        </div>

    </div>

</main>