<main>
    <div class="container">

        <div id="text">

            <div id="divtext">
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Provident quidem doloremque dolorem harum obcaecati asperiores ea, dolor, aliquam quis maxime quas reiciendis ab deserunt voluptates nostrum, atque soluta! Consectetur, delectus.</p>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Provident quidem doloremque dolorem harum obcaecati asperiores ea, dolor, aliquam quis maxime quas reiciendis ab deserunt voluptates nostrum, atque soluta! Consectetur, delectus.</p>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Provident quidem doloremque dolorem harum obcaecati asperiores ea, dolor, aliquam quis maxime quas reiciendis ab deserunt voluptates nostrum, atque soluta! Consectetur, delectus.</p>

            </div>


            <div id="section">
                <h3>Cvičení</h3>
            </div>


            <div id="divbars">



                <div>
                    <img src="" alt="">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias at error dolores pariatur assumenda repellendus adipisci necessitatibus. Adipisci, rem doloremque aliquam obcaecati autem minus est saepe dolor nam dolores maiores!</p>
                </div>

                <div>
                    <img src="" alt="">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias at error dolores pariatur assumenda repellendus adipisci necessitatibus. Adipisci, rem doloremque aliquam obcaecati autem minus est saepe dolor nam dolores maiores!</p>
                </div>

                <div>
                    <img src="" alt="">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias at error dolores pariatur assumenda repellendus adipisci necessitatibus. Adipisci, rem doloremque aliquam obcaecati autem minus est saepe dolor nam dolores maiores!</p>
                </div>

                <div>
                    <img src="" alt="">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias at error dolores pariatur assumenda repellendus adipisci necessitatibus. Adipisci, rem doloremque aliquam obcaecati autem minus est saepe dolor nam dolores maiores!</p>
                </div>

                <div>
                    <img src="" alt="">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias at error dolores pariatur assumenda repellendus adipisci necessitatibus. Adipisci, rem doloremque aliquam obcaecati autem minus est saepe dolor nam dolores maiores!</p>
                </div>

                <div>
                    <img src="" alt="">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias at error dolores pariatur assumenda repellendus adipisci necessitatibus. Adipisci, rem doloremque aliquam obcaecati autem minus est saepe dolor nam dolores maiores!</p>
                </div>

            </div>


        </div>



        <div id="sidediv">

            <div id="profile-info">
                <h3>Profile</h3>
                <p>Jmeno: <?php echo (!empty($_SESSION['uzivatel']))?$_SESSION['uzivatel']['jmeno']:'Nikdo neni prihlaseny'; ?></p>
                <p>Streak:</p>
            </div>

            <div id="nastenka">
                <h3>Nástěnka</h3>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia, tempore, consectetur ea quas amet molestiae in numquam natus fuga illo veritatis sit optio nisi cumque asperiores ipsum reiciendis velit aliquid.</p>
            </div>

        </div>

    </div>

</main>


<footer>
    <p>Blagablugah</p>
</footer>