<pre> <!-- VYPIS vseho *** POTOM SMAZAT -->
    <?php
    print_r($this->data['uzivatel'] ?? '');
    ?>
</pre>




<p><?php // JESTLIZE JE CHYBA, TAK UKAZ ZPRAVU A ZOBRAZ ODKAZ NA VSECHNY
    if (isset($_SESSION["zpravy"]["uzivatel"]["chybaNacteni"])) {
        echo $_SESSION["zpravy"]["uzivatel"]["chybaNacteni"] ;
        echo "<br>";
        echo "<a href=''>Jit na uvodni obrazovku</a>";
    }

    ?>
</p>