<script src="../js/vytvareniPrispevku/selectory.js"></script>
<script src="../js/vytvareniPrispevku/inputFileReader.js"></script>
<script src="../js/vytvareniPrispevku/comToPhp.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mammoth/1.4.4/mammoth.browser.min.js"></script>

<body>

<form method="POST">

    <div class="input-group">
        <label for="typPrispevkuId">Typ prispevku</label>
        <select name="typPrispevku" id="typPrispevkuId" required>
            <?php
            foreach ($this->data['typyPrispevku'] as $tp) {
                if ($tp['Id'] != 4){
                    echo "<option value=".$tp['Id'].">".$tp["typ"]."</option>";
                }
            }
            ?>
        </select>
    </div>

    <div class="input-group">
        <label for="vyberKnizky">Knihy</label>
        <select name="vyberKnizky" id="vyberKnizky" required>
            <?php if (isset($this->data['predurcenaKnihaString'])) {
                echo "<option selected value='" . $this->data['predurcenaKnihaId'] . "'>" . $this->data['predurcenaKnihaString'] . "</option>";
            }
            else {
                foreach ($this->data['vsechnyKnihy'] as $kniha) {
                    echo "<option value='" . $kniha['idKniha'] . "'>" . $kniha['nazevKniha'] . " - " . $kniha['jmenoAutora'] ." ". $kniha['prijmeniAutora'] . "</option>";
                }
            }
            ?>
        </select>
    </div>

    <div class="input-group">
        <label for="nazevPrispevku">Nazev prispevku</label>
        <input type="text" name="nazevPrispevku" id="nazevPrispevku" required>
    </div>

    <div class="input-group">
        <label for="fileInput">Nahrat vlastni dokument</label>
        <input type="file" id="fileInput" name="fileInput">
    </div>

    <div class="input-group">
        <label>
            <textarea name="content" id="hlavniEditor"></textarea>
            <textarea name="textareaContentJakoHtml" id="textareaContentJakoHtml" required></textarea>
        </label>
    </div>

    <div id="zahoditOkenko" hidden="hidden">
        <p>Chcete zahodit dosud nasapny text?</p>
        <button type="button" id="zahoditA">ANO</button>
        <button type="button" id="zahoditN">NE</button>
    </div>

    <button type="submit">Nahrat</button>

</form>

<div id="zahoditOkenko" hidden="hidden">
    <p>Chcete zahodit dosud nasapny text?</p>
    <button id="zahoditA">ANO</button>
    <button id="zahoditN">NE</button>
</div>


</body>
<script src="../ckeditor/ckeditor.js"></script>
<script>
    CKEDITOR.replace('content', {
        language: 'cs',
        customConfig: '../js/vytvareniPrispevku/ckEditorConfig.js',
        skin: 'n1theme',
        height: '400px'
    });
</script>
