

<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>-->
<!--<script src="../js/vytvareniKvizu.js"></script>-->
<script src="../js/vytvareniKvizu.js"></script>

<main>
    <form action="" method="post">

        <div class="centerKviz">
            <label for="nazevKvizu">Nazev kvizu</label>
            <input type="text" name="nazevKvizu" id="nazevKvizu">

            <label for="vyberKnihy">Vyber knihy</label>
            <select name="kniha" id="vyberKnihy">
                <?php if (isset($this->data['predurcenaKnihaString'])): ?>
                    <option selected value="<?= $this->data['predurcenaKnihaId'] ?>">
                        <?= $this->data['predurcenaKnihaString'] ?>
                    </option>
                <?php else: ?>
                    <?php foreach ($this->data['vsechnyKnihy'] as $kniha): ?>
                        <option value="<?= $kniha['idKniha'] ?>">
                            <?= $kniha['nazevKniha'] ?> - <?= $kniha['jmenoAutora'] ?> <?= $kniha['prijmeniAutora'] ?>
                        </option>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>

            <div id="vytvareniKvizu">
                <div id="vyslednyFormular">
                    <div id="strukturaFormulare"></div>
                    <input type="text" name="spravneOdpovedi" id="spravneOdpovediInput" value="" readonly hidden>
                </div>

                <div id="graficke">
                    <div id="grafickeVkladaniDiv"></div>
                    <button id="vytvoritOtazku" type="button">Vytvorit otazku</button>
                </div>
            </div>

            <input type="hidden" id="teloKvizu" name="teloKvizu">
            <input type="submit" value="Vytvorit kviz" id="vyrvoritKviz">
        </div>

    </form>
</main>
