<style>
    #vytvareniKvizu {
    display: flex;
    }
    #vyslednyFormular, #graficke {
        width: 50%;
    }
    #grafickeVkladaniDiv {
        padding: 0;
    }
    #graficke {
        background-color: #1a8fce;
    }

    .otazka {
        background-color: #2e9ad0;
        margin: 10px 0 ;
    }
    .odpovediDiv {
        background-color: #b7d9ee;
    }
    div, select, input {
        margin: 10px 0;
    }

    .inputKvizuSpatne {
        background-color: #f58e8e;
    }
</style>

<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>-->
<!--<script src="../js/vytvareniKvizu.js"></script>-->
<script src="../js/vytvareniKvizu.js"></script>

<main>
    <form action="" method="post">

        <label for="nazevKvizu">Nazev kvizu</label>
        <input type="text" name="nazevKvizu" id="nazevKvizu" required>

        <label for="vyberKnihy"></label>
        <select name="kniha" id="vyberKnihy">
        <?php if (isset($this->data['predurcenaKnihaString'])) {
            echo "<option selected value='" . $this->data['predurcenaKnihaId'] . "'>" . $this->data['predurcenaKnihaString'] . "</option>";
        }
        else {
            foreach ($this->data['vsechnyKnihy'] as $kniha) {
                echo "<option value='" . $kniha['idKniha'] . "'>" . $kniha['nazevKniha'] . " - " . $kniha['jmenoAutora'] ." ". $kniha['prijmeniAutora'] . "</option>";
            }
        }
        ?>
        </select>

        <div id="vytvareniKvizu">
            <div id="vyslednyFormular"style="background-color: #aacfee">

                <div id="strukturaFormulare"></div>

                <label for="spravneOdpovediInput">Spravne odpovedi</label>
                <input type="text" name="spravneOdpovedi" id="spravneOdpovediInput" value="" readonly>

            </div>
            <div id="graficke">
                <div id="grafickeVkladaniDiv" style="background-color: #0e7fe1">
                </div>
                <button id="vytvoritOtazku" type="button">Vytvorit otazku</button>
            </div>

        </div>


        <input type="hidden" id="teloKvizu" name="teloKvizu">
        <input type="submit" value="Vytvorit kviz" id="vytvoritKviz">
    </form>


</main>